apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flask-mysql-crud-app
spec:
  serviceName: "flask-mysql-crud-app"
  replicas: 1
  selector:
    matchLabels:
      app: flask-mysql-crud-app
  template:
    metadata:
      labels:
        app: flask-mysql-crud-app
    spec:
      containers:
      - name: app
        image: flask-mysql-crud-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: M@tech@pp1234
        - name: MYSQL_DB
          value: crud
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: M@tech@pp1234
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
